version: '3.4'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=dbAPIWarren
      - MYSQL_ROOT_PASSWORD=warrenbanco1224
    ports:
      - '3307:3306'