version: '3.4'
services:
  mysql:
    image: mysql
    container_name: dbWarren
    restart: always
    ports:
      - "4775:4775"
    environment:
      - MYSQL_DATABASE=dbAPIWarren
      - MYSQL_ROOT_PASSWORD= warrenbanco1224
